# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import count_pb2 as count__pb2


class CountNumStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.QuickCount = channel.unary_unary(
                '/count.CountNum/QuickCount',
                request_serializer=count__pb2.CountRequest.SerializeToString,
                response_deserializer=count__pb2.CountReply.FromString,
                )


class CountNumServicer(object):
    """Missing associated documentation comment in .proto file."""

    def QuickCount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CountNumServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'QuickCount': grpc.unary_unary_rpc_method_handler(
                    servicer.QuickCount,
                    request_deserializer=count__pb2.CountRequest.FromString,
                    response_serializer=count__pb2.CountReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'count.CountNum', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CountNum(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def QuickCount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/count.CountNum/QuickCount',
            count__pb2.CountRequest.SerializeToString,
            count__pb2.CountReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
