# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: count.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63ount.proto\x12\x05\x63ount\"7\n\x0c\x43ountRequest\x12\x0c\n\x04numa\x18\x01 \x01(\x05\x12\x0c\n\x04numb\x18\x02 \x01(\x05\x12\x0b\n\x03opt\x18\x03 \x01(\x05\"\x1b\n\nCountReply\x12\r\n\x05reNum\x18\x01 \x01(\x05\x32@\n\x08\x43ountNum\x12\x34\n\nQuickCount\x12\x13.count.CountRequest\x1a\x11.count.CountReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'count_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_COUNTREQUEST']._serialized_start=22
  _globals['_COUNTREQUEST']._serialized_end=77
  _globals['_COUNTREPLY']._serialized_start=79
  _globals['_COUNTREPLY']._serialized_end=106
  _globals['_COUNTNUM']._serialized_start=108
  _globals['_COUNTNUM']._serialized_end=172
# @@protoc_insertion_point(module_scope)
